### ISSUE TITLE
Failed to fetch data when clicking a link with a union type

### ISSUE THREAD

**Issue by AnsonHwang86** [edgedb/edgedb-ui#99]
Say we have schema as following.

```
module default {
    abstract type Place {
        property name -> str;
        property abbr -> str;
    }

    type Country extending Place {
    }

    type State extending Place {
        required link country -> Country;
    }

    type City extending Place {
        required link state -> State;
    }

    type District extending Place {
        required link city -> City;
    }

    type Street extending Place {
        required link districtOrCity -> District|City; # Assumed there are some Street belong to City instead of District.
    }
}
```

And we fill some data via edgedb ui. 
some `Street` link to `City` directly. 

But it fail to read the data when click the link to City from Street.

![image](https://user-images.githubusercontent.com/16233397/207223450-913ab1c4-a5c3-42ed-9842-f269101fab41.png)

It will fail as following.

![image](https://user-images.githubusercontent.com/16233397/207223548-a128760a-4718-4d30-9d8b-03de6a836013.png)

**Comment by raddevon** [comment]
I was able to reproduce this.

EdgeDB version: 2.8+12da66f
EdgeDB CLI version: 2.2.6+7eabbf9
OS: macOS 13.0.1

Seems to be the union type of the link that causes the problem. If I run a migration to change that link to `City` only instead of `City|District`, I'm able to click through the link and load the street's `City` object in the UI.
